import { Link } from "react-router-dom";
import {
  Building2, Target, MapPin, Calendar, DollarSign,
  Users, ShieldAlert, Shield, TrendingUp, FileText,
  ArrowLeft, Check, Circle,
} from "lucide-react";
import { Section } from "@/pages/ProjectBuilder";

interface SectionData {
  section: Section;
  data: Record<string, any>;
  completed: boolean;
}

interface BuilderSidebarProps {
  projectName: string;
  activeSection: Section;
  sectionData: Record<Section, SectionData>;
  onSectionChange: (section: Section) => void;
}

const SECTION_CONFIG: Record<Section, { label: string; icon: any; autoGenerated?: boolean; comingSoon?: boolean }> = {
  "project-scope": { label: "Project Scope", icon: Building2 },
  "vision-market": { label: "Vision & Market Case", icon: Target },
  "site-location": { label: "Site & Location", icon: MapPin },
  "project-schedule": { label: "Project Schedule", icon: Calendar },
  "budget-capital": { label: "Budget & Sources/Uses", icon: DollarSign },
  "project-team": { label: "Project Team", icon: Users },
  "risk-assessment": { label: "Risk Assessment", icon: ShieldAlert },
  "resilience-factors": { label: "Resilience Factors", icon: Shield },
  "feasibility": { label: "Feasibility Analysis", icon: TrendingUp },
  "executive-summary": { label: "Executive Summary", icon: FileText, autoGenerated: true },
};

const SECTIONS: Section[] = [
  "project-scope", "vision-market", "site-location", "project-schedule",
  "budget-capital", "project-team", "risk-assessment", "resilience-factors",
  "feasibility", "executive-summary",
];

export const BuilderSidebarContent = ({
  projectName,
  activeSection,
  sectionData,
  onSectionChange,
}: BuilderSidebarProps) => {
  return (
    <div className="h-full bg-card flex flex-col">
      {/* Project Header */}
      <div className="p-6 border-b border-border">
        <h2 className="font-bold text-lg text-foreground truncate" title={projectName}>
          {projectName}
        </h2>
        <p className="text-sm text-muted-foreground mt-1">Development Package</p>
      </div>

      {/* Section Navigation */}
      <nav className="flex-1 py-2 overflow-y-auto">
        {SECTIONS.map((section, index) => {
          const config = SECTION_CONFIG[section];
          const Icon = config.icon;
          const isActive = activeSection === section;
          const isCompleted = sectionData[section]?.completed;

          return (
            <button
              key={section}
              onClick={() => onSectionChange(section)}
              className={`w-full flex items-center gap-3 px-5 py-2.5 text-left transition-all duration-200 ${
                isActive
                  ? "bg-primary/10 border-l-4 border-primary text-foreground"
                  : "hover:bg-muted border-l-4 border-transparent text-muted-foreground hover:text-foreground"
              }`}
            >
              {/* Number */}
              <span className={`text-xs font-medium w-4 text-center flex-shrink-0 ${
                isActive ? "text-primary" : "text-muted-foreground/60"
              }`}>
                {index + 1}
              </span>

              {/* Icon */}
              <div
                className={`w-7 h-7 rounded-lg flex items-center justify-center flex-shrink-0 ${
                  isActive
                    ? "icon-gradient"
                    : isCompleted
                    ? "bg-green-100"
                    : config.comingSoon
                    ? "bg-muted/60"
                    : "bg-muted"
                }`}
              >
                <Icon
                  className={`w-3.5 h-3.5 ${
                    isActive
                      ? "text-primary-foreground"
                      : isCompleted
                      ? "text-green-600"
                      : config.comingSoon
                      ? "text-muted-foreground/40"
                      : "text-muted-foreground"
                  }`}
                />
              </div>

              {/* Label */}
              <div className="flex-1 min-w-0">
                <span className={`block text-sm font-medium leading-tight ${
                  isActive ? "text-foreground" : config.comingSoon ? "text-muted-foreground/60" : ""
                }`}>
                  {config.label}
                </span>
                {config.autoGenerated && (
                  <span className="text-xs text-muted-foreground">Auto-generated</span>
                )}
                {config.comingSoon && (
                  <span className="text-xs text-muted-foreground/50">Coming Soon</span>
                )}
              </div>

              {/* Status Indicator */}
              {isCompleted ? (
                <Check className="w-4 h-4 text-green-600 flex-shrink-0" />
              ) : (
                <Circle className={`w-4 h-4 flex-shrink-0 ${
                  config.comingSoon ? "text-muted-foreground/20" : "text-muted-foreground/40"
                }`} />
              )}
            </button>
          );
        })}
      </nav>

      {/* Back to Dashboard */}
      <div className="p-4 border-t border-border">
        <Link
          to="/dashboard"
          className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors px-2 py-2"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to Dashboard
        </Link>
      </div>
    </div>
  );
};

export const BuilderSidebar = (props: BuilderSidebarProps) => (
  <aside className="hidden lg:flex fixed left-0 top-0 h-screen w-[280px] border-r border-border shadow-sm flex-col">
    <BuilderSidebarContent {...props} />
  </aside>
);
